export const ActionTypes={
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    SET_SEARCH_TERM: 'SET_SEARCH_TERM',
    SET_PLACE_ORDER : 'SET_PLACE_ORDER'
        // other action types...
}
